### ISSUE TITLE
About the accuracy of adversarial examples

### ISSUE THREAD

**Issue by lith0613** [MadryLab/cifar10_challenge#10]
I download the two 'secret model'  from the web url in fetch_model.py,  and load the model weights.  When I use the adversarial examples generated from my own method,  I found the test accuracy of the naturally_trained model is even better than the accuracy of adv_trained model.  I don't know why that happens, can you give some explanation ?

**Comment by dtsip** [comment]
This can happen if you don't construct strong enough adversarial examples. I would recommend comparing your attack to one of the strong baselines already included in the repo.
