### ISSUE TITLE
Image Channels

### ISSUE THREAD

**Issue by rajasekharponakala** [MadryLab/cifar10_challenge#11]
Hi Team,

For example, if a CNN model (say, image classification) is trained on a 1-channel (grayscale) inputs, how can we deal with the perturbations or l-norm constraints? any thoughts? 
Thanks.

**Comment by dtsip** [comment]
Hi, perturbations are defined based on the single channel inputs. An L-infinity perturbations allows the adversary to perturb each pixel of this grayscale image by epsilon.
