### ISSUE TITLE
Base network questions and implementation.

### ISSUE THREAD

**Issue by JonathanCMitchell** [MadryLab/cifar10_challenge#13]
Does anybody know if there is a PyTorch implementation of the Wide ResNet network specifically mentioned in this repository. I have found some but they are 30x10 instead of 28x10? Additionally is the standard (non-wide) ResNet a ResNet101?

**Comment by dtsip** [comment]
We recently released a PyTorch library for adversarial training (along with pre-trained models) here: https://github.com/MadryLab/robustness . You can find standard architectures such as ResNet50 there.

I don't think that the non-wide ResNet is exactly ResNet101 (I'm not very familiar with the terminology though). It is based on one of the TensorFlow tutorials.

**Comment by JonathanCMitchell** [comment]
Hi thanks for your response. 

It seems that I am still a bit confused. There is a comment on line: https://github.com/MadryLab/cifar10_challenge/blob/master/model.py#L50
That says "uncomment the following codes to use WideResNet" however it is unclear on which lines to actually uncomment because there isn't any code that is commented out. Therefore if I use the default code and obtain a model using:
`python fetch_model.py --name adv_trained` will that be a ResNet101 as shown here:https://github.com/MadryLab/robustness/blob/master/robustness/cifar_models/resnet.py#L145
Or is it a Wide ResNet? And if so where do I find the exact model architecture for it? 

Thanks again!

**Comment by dtsip** [comment]
Oh I see, apologies for the unclear comment.

The released `adv_trained` model corresponds to the wide variant which is the default model of the repo. The non-wide variant corresponds to setting `filters = [16, 16, 32, 64]` (updated comment to reflect/clarify that) for which we don't have a public pre-trained model.

In any case, the exact model architecture used is defined in https://github.com/MadryLab/cifar10_challenge/blob/master/model.py#L50 .
