### ISSUE TITLE
Same accuracy logged twice

### ISSUE THREAD

**Issue by JonathanCMitchell** [MadryLab/cifar10_challenge#14]
Why is the accuracy logged out twice to tensorboard for the adversarial samples in https://github.com/MadryLab/cifar10_challenge/blob/master/train.py#L76. It seems that these are just duplicates.

**Comment by dtsip** [comment]
Yes, they are duplicates, but we log them under different tags. This is useful when training a bunch of models and you want to compare all the training accuracies in one plot but also be able to compare train and test accuracy of a single model in one plot.
