### ISSUE TITLE
About the convergence of training.

### ISSUE THREAD

**Issue by anonymous530** [MadryLab/cifar10_challenge#17]
Hello, thanks for your  great work. I wonder as the training going on,  how to judge the convergence of training? Just according to the curves of loss?

**Comment by dtsip** [comment]
Mostly yes. Looking at the training and test loss/accuracy is what we typically do.

**Comment by anonymous530** [comment]
> Mostly yes. Looking at the training and test loss/accuracy is what we typically do.

Thanks.
