### ISSUE TITLE
About the network architecture

### ISSUE THREAD

**Issue by dongyp13** [MadryLab/cifar10_challenge#23]
Hi,

I have a question about the network architecture. As you commented in [https://github.com/MadryLab/cifar10_challenge/blob/master/model.py#L50](https://github.com/MadryLab/cifar10_challenge/blob/master/model.py#L50), it is a `w28-10` wide residual network. However, when I looked at the original implementation of wide resnet at [https://github.com/tensorflow/models/blob/master/research/resnet/resnet_model.py#L87-L92](https://github.com/tensorflow/models/blob/master/research/resnet/resnet_model.py#L87-L92), the `hps.num_residual_units` needs to be set as `4`. But it is set as `5` in your code, which corresponds to a `w34-10` network?

**Comment by dtsip** [comment]
Thank for catching this! We probably missed this part of the code when making the model wider. I am not super familiar with the wresnet terminology so this might indeed not be a `w28-10` model. I will update the comment to avoid further confusion.
