### ISSUE TITLE
clean accuracy on adversarially trained cifar10 resnet 18

### ISSUE THREAD

**Issue by wahrheit-git** [MadryLab/cifar10_challenge#25]
Can you tell what is the clean accuracy of the adv. trained model here (used in the leaderboard)?
Also what is the number of iterations for PGD used for adv. training?

**Comment by dtsip** [comment]
The clean accuracy is 87.14%.

The model was trained as described in the paper: 7 steps of PGD, with random start, and a step size of 2 (out of 255 per pixel).
