### ISSUE TITLE
pytorch definition of the model 

### ISSUE THREAD

**Issue by kartikgupta-at-anu** [MadryLab/cifar10_challenge#26]
Is there a pytorch definition and pytorch model weights of the architecture used for the white board leaderboard? 
We would like to try our attack on your challenge but unfortunately our code is written in PyTorch.

If there is any other way, please let me know?

**Comment by dtsip** [comment]
We don't really have an equivalent PyTorch implementation (or plans to release one).

That being said, we recently released an adversarial training library in PyTorch: https://github.com/MadryLab/robustness . It has pretrained CIFAR models for L2 and Linf adversaries. This is not really a robustness challenge, but is probably still useful for comparing a new attack to PGD.
