### ISSUE TITLE
The config of training robust model for CIFAR10.

### ISSUE THREAD

**Issue by ylsung** [MadryLab/cifar10_challenge#27]
In this repository, the PGD attack applied in training the robust model was using 7 steps of size 2 shown in the [paper](https://arxiv.org/pdf/1706.06083.pdf) or using 10 steps of size 2 shown in the [config](https://github.com/MadryLab/cifar10_challenge/blob/master/config.json)? Thank you.

**Comment by dtsip** [comment]
7 steps, as mentioned in the paper. The default config is just an example.

Note that when you download models with `python fetch_model` there is a `config.json` inside the resulting folder that contains the exact parameters used.
