### ISSUE TITLE
cifar_input.py Function get_next_batch() has a small bug.

### ISSUE THREAD

**Issue by Mrxiaoyuer** [MadryLab/cifar10_challenge#3]
Hi there,

Thanks a lot for the open sourced project!

I recently found that the function get_next_batch() in cifar_input.py has a small bug.
In cifar_input.py line 132 and 142,

`       actual_batch_size = min(batch_size, self.n - self.batch_start)

        if actual_batch_size < batch_size:

            if reshuffle_after_pass:

                self.cur_order = np.random.permutation(self.n)

            self.batch_start = 0

        batch_end = self.batch_start + batch_size

        batch_xs = self.xs[self.cur_order[self.batch_start : batch_end], ...]

        batch_ys = self.ys[self.cur_order[self.batch_start : batch_end], ...]

        self.batch_start += actual_batch_size`

The final line here should be self.batch_start += batch_size, since the generated batch contains (batch_size) images and labels.

For example, when we just take every image out and start over again, this will cause actual_batch_size = 0, then self.batch_start will not update in the first round and there will be two same batch generated.

**Comment by dtsip** [comment]
Yes, you are right. This means that we were reusing part of the last batch each epoch. Just pushed a fix. Thanks for letting us know!
