### ISSUE TITLE
pretrained model link expired

### ISSUE THREAD

**Issue by hank08tw** [MadryLab/cifar10_challenge#30]
Can anyone provide new link to download pretrained model in fetch_model.py?
I got urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable> when I run python fetch_model.py natural

**Comment by dtsip** [comment]
I am unable to reproduce this. Running the same thing on my side gives:
```
$ python fetch_model.py natural
Downloading models
SHA256 hash: 6af2addfc5bc75e3b16b8654c907a8dfaebeffc600871115460063ade1cd1ee7
Extracting model
Extracted model in models/
```

In any case, the direct download link for each model can be found in the `fetch_model.py` code (specifically [here](https://github.com/MadryLab/cifar10_challenge/blob/master/fetch_model.py#L17)).
